const sampleImages = [
    'https://upload.wikimedia.org/wikipedia/commons/a/a4/2019_Toyota_Corolla_Icon_Tech_VVT-i_Hybrid_1.8.jpg',
    'https://www.worldcoffeeportal.com/getattachment/a1fb8071-8708-48a5-879a-7f53d1775dd4/angelica-reyes-6xBvVSs2G8c-unsplash-(1).jpg.aspx?lang=en-GB&width=700&height=466',
    'https://theimperialtours.com/wp-content/uploads/2024/09/tajmahajnight.jpg',
    'https://images.healthshots.com/healthshots/en/uploads/2023/10/04172423/best-coffee-brands-2.jpg',
];

const getRandomImages = () => {
    const count = Math.floor(Math.random() * 4) + 1; // 1 to 8 images
    const images = [];
    for (let i = 0; i < count; i++) {
        const randomIndex = Math?.floor(Math.random() * sampleImages.length);
        images.push(sampleImages[randomIndex]);
    }
    return images;
};

export const fakePosts = [
    {
        id: '1',
        name: 'Emily Johnson',
        postTitle: 'Morning vibes ☀️',
        postImage: getRandomImages(),
        postTime: '2 hours ago',
        likeCount: 120,
        commentCount: 14,
        favourite: false,
        userProfileImage: 'https://randomuser.me/api/portraits/women/21.jpg',
        location: 'New York, USA',
    },
    {
        id: '2',
        name: 'David Kim',
        postTitle: 'City lights at night 🌃',
        postImage: getRandomImages(),
        postTime: '5 hours ago',
        likeCount: 342,
        commentCount: 38,
        favourite: true,
        userProfileImage: 'https://randomuser.me/api/portraits/men/44.jpg',
        location: 'Los Angeles, USA',
    },
    {
        id: '3',
        name: 'Sophia Lee',
        postTitle: 'Weekend getaway 💖',
        postImage: getRandomImages(),
        postTime: '1 day ago',
        likeCount: 510,
        commentCount: 65,
        favourite: false,
        userProfileImage: 'https://randomuser.me/api/portraits/women/32.jpg',
        location: 'Bali, Indonesia',
    },
    {
        id: '4',
        name: 'James Carter',
        postTitle: 'Coffee and code ☕💻',
        postImage: getRandomImages(),
        postTime: '30 minutes ago',
        likeCount: 89,
        commentCount: 12,
        favourite: false,
        userProfileImage: 'https://randomuser.me/api/portraits/men/56.jpg',
        location: 'San Francisco, USA',
    },
    {
        id: '5',
        name: 'Ava Thompson',
        postTitle: 'Hiking to the top! 🏞️',
        postImage: getRandomImages(),
        postTime: '3 days ago',
        likeCount: 470,
        commentCount: 44,
        favourite: true,
        userProfileImage: 'https://randomuser.me/api/portraits/women/45.jpg',
        location: 'Swiss Alps',
    },
    {
        id: '6',
        name: 'Liam Smith',
        postTitle: 'Lazy Sunday afternoon...',
        postImage: getRandomImages(),
        postTime: '4 hours ago',
        likeCount: 145,
        commentCount: 19,
        favourite: false,
        userProfileImage: 'https://randomuser.me/api/portraits/men/60.jpg',
        location: 'Toronto, Canada',
    },
    {
        id: '7',
        name: 'Mia Walker',
        postTitle: 'Art in motion 🎨',
        postImage: getRandomImages(),
        postTime: '6 hours ago',
        likeCount: 289,
        commentCount: 32,
        favourite: false,
        userProfileImage: 'https://randomuser.me/api/portraits/women/38.jpg',
        location: 'Paris, France',
    },
    {
        id: '8',
        name: 'Noah Anderson',
        postTitle: 'Gym time 💪',
        postImage: getRandomImages(),
        postTime: '1 hour ago',
        likeCount: 198,
        commentCount: 18,
        favourite: true,
        userProfileImage: 'https://randomuser.me/api/portraits/men/33.jpg',
        location: 'Miami, USA',
    },
    {
        id: '9',
        name: 'Isabella Martinez',
        postTitle: 'Foodie finds 🍜',
        postImage: getRandomImages(),
        postTime: '8 hours ago',
        likeCount: 322,
        commentCount: 28,
        favourite: true,
        userProfileImage: 'https://randomuser.me/api/portraits/women/50.jpg',
        location: 'Tokyo, Japan',
    },
    {
        id: '10',
        name: 'William Scott',
        postTitle: 'Throwback to this view 😍',
        postImage: getRandomImages(),
        postTime: '2 days ago',
        likeCount: 390,
        commentCount: 49,
        favourite: false,
        userProfileImage: 'https://randomuser.me/api/portraits/men/77.jpg',
        location: 'Santorini, Greece',
    },
];



export const ExploreEvent = [
    {
        id: 1,
        username: 'john doe',
        profileImage: 'https://randomuser.me/api/portraits/men/1.jpg',
        location: 'New York City',
        invited: 120,
        joined: 75,
        eventImages: [
            'https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg',
            'https://media.istockphoto.com/id/479977238/photo/table-setting-for-an-event-party-or-wedding-reception.jpg?s=612x612&w=0&k=20&c=yIKLzW7wMydqmuItTTtUGS5cYTmrRGy0rXk81AltdTA=',
            'https://marketing-cdn.tickettailor.com/ZgP1j7LRO5ile62O_HowdoyouhostasmallcommunityeventA10-stepguide%2CMiniflagsattheevent.jpg?auto=format,compress',
        ],
        description:
            'Join us for an amazing rooftop party with live music and drinks!',
        dateTime: '2025-05-15 7:00 PM',
    },
    {
        id: 2,
        username: 'jane smith',
        profileImage: 'https://randomuser.me/api/portraits/women/2.jpg',
        location: 'Los Angeles',
        invited: 80,
        joined: 60,
        eventImages: [
            'https://media.istockphoto.com/id/479977238/photo/table-setting-for-an-event-party-or-wedding-reception.jpg?s=612x612&w=0&k=20&c=yIKLzW7wMydqmuItTTtUGS5cYTmrRGy0rXk81AltdTA=',
            'https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg',
            'https://marketing-cdn.tickettailor.com/ZgP1j7LRO5ile62O_HowdoyouhostasmallcommunityeventA10-stepguide%2CMiniflagsattheevent.jpg?auto=format,compress',
        ],
        description:
            'Sunset yoga session at the beach, followed by a healthy brunch!',
        dateTime: '2025-05-16 6:00 AM',
    },
    {
        id: 3,
        username: 'michael brown',
        profileImage: 'https://randomuser.me/api/portraits/men/3.jpg',
        location: 'Chicago',
        invited: 200,
        joined: 150,
        eventImages: [
            'https://marketing-cdn.tickettailor.com/ZgP1j7LRO5ile62O_HowdoyouhostasmallcommunityeventA10-stepguide%2CMiniflagsattheevent.jpg?auto=format,compress',
            'https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg',
            'https://media.istockphoto.com/id/479977238/photo/table-setting-for-an-event-party-or-wedding-reception.jpg?s=612x612&w=0&k=20&c=yIKLzW7wMydqmuItTTtUGS5cYTmrRGy0rXk81AltdTA=',
        ],
        description:
            'Networking event for young entrepreneurs. Drinks and snacks provided.',
        dateTime: '2025-05-20 5:00 PM',
    },
];









export const Fakeshops = [
    {
        id: '1',
        name: 'Gadget Hub',
        image: {
            uri: 'https://images.pexels.com/photos/1819644/pexels-photo-1819644.jpeg',
        },
        location: 'New York, USA',
        description: 'Best electronics and gadgets.',
        rating: 4.5,
    },
    {
        id: '2',
        name: 'Urban Styles',
        image: {
            uri: 'https://images.unsplash.com/photo-1605733160314-4f6b3ca9d925',
        },
        location: 'Los Angeles, USA',
        description: 'Trendy fashion apparel.',
        rating: 4.0,
    },
    {
        id: '3',
        name: 'Book Nook',
        image: {
            uri: 'https://images.pexels.com/photos/1370296/pexels-photo-1370296.jpeg',
        },
        location: 'Chicago, USA',
        description: 'Wide variety of books and stationery.',
        rating: 4.2,
    },
    {
        id: '4',
        name: 'Fitness Zone',
        image: {
            uri: 'https://images.unsplash.com/photo-1583454110558-0212df0f8f61',
        },
        location: 'Houston, USA',
        description: 'Your fitness essentials shop.',
        rating: 4.6,
    },
    {
        id: '5',
        name: 'Home Essentials',
        image: {
            uri: 'https://images.pexels.com/photos/3965549/pexels-photo-3965549.jpeg',
        },
        location: 'San Diego, USA',
        description: 'Furniture and home décor.',
        rating: 4.3,
    },
    {
        id: '6',
        name: 'FreshMart',
        image: {
            uri: 'https://images.unsplash.com/photo-1606813902917-094543b4fcf5',
        },
        location: 'Miami, USA',
        description: 'Organic groceries and fresh produce.',
        rating: 4.1,
    },
    {
        id: '7',
        name: 'Tech World',
        image: {
            uri: 'https://images.pexels.com/photos/18105/pexels-photo.jpg',
        },
        location: 'Austin, USA',
        description: 'All the latest in tech and gadgets.',
        rating: 4.8,
    },
    {
        id: '8',
        name: 'Beauty Bliss',
        image: {
            uri: 'https://images.unsplash.com/photo-1622658411584-66e0178d13e0',
        },
        location: 'Seattle, USA',
        description: 'Beauty products and skincare essentials.',
        rating: 4.4,
    },
    {
        id: '9',
        name: 'Pet Palace',
        image: {
            uri: 'https://images.pexels.com/photos/5731865/pexels-photo-5731865.jpeg',
        },
        location: 'Boston, USA',
        description: 'Everything your pet needs!',
        rating: 4.7,
    },
    {
        id: '10',
        name: 'KitchenPro',
        image: {
            uri: 'https://images.unsplash.com/photo-1588854337236-d27b50a1184d',
        },
        location: 'Denver, USA',
        description: 'High-quality kitchenware and tools.',
        rating: 4.2,
    },
];




export const products = [
    {
        id: '1',
        image: { uri: 'https://plus.unsplash.com/premium_photo-1661769750859-64b5f1539aa8?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZHVjdCUyMGltYWdlfGVufDB8fDB8fHww' },
        name: 'Wireless Headphones',
        description: 'Noise cancelling, Bluetooth 5.0',
        actualPrice: 120,
        discountPrice: 89,
        shopName: 'Gadget Hub',
        rating: 4.5,
    },
    {
        id: '2',
        image: { uri: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?auto=format&fit=crop&w=600&q=60' },
        name: 'Smart Watch',
        description: 'Waterproof, heart-rate monitor',
        actualPrice: 99,
        discountPrice: 75,
        shopName: 'Tech World',
        rating: 4.7,
    },
    {
        id: '3',
        image: { uri: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?auto=format&fit=crop&w=600&q=60' },
        name: 'Coffee Maker',
        description: 'Auto brew, 1.2L capacity',
        actualPrice: 150,
        discountPrice: 120,
        shopName: 'Home Essentials',
        rating: 4.3,
    },
    {
        id: '4',
        image: { uri: 'https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?auto=format&fit=crop&w=600&q=60' },
        name: 'Bluetooth Speaker',
        description: 'Portable and waterproof',
        actualPrice: 80,
        discountPrice: 59,
        shopName: 'Gadget Hub',
        rating: 4.6,
    },
    {
        id: '5',
        image: { uri: 'https://plus.unsplash.com/premium_photo-1661769750859-64b5f1539aa8?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHJvZHVjdCUyMGltYWdlfGVufDB8fDB8fHww' },
        name: 'VR Headset',
        description: 'Immersive virtual reality experience',
        actualPrice: 200,
        discountPrice: 160,
        shopName: 'Virtual Vibes',
        rating: 4.4,
    },
    {
        id: '6',
        image: { uri: 'https://as2.ftcdn.net/jpg/03/98/30/51/220_F_398305176_wQvP7CUGfcmC6A2sNd3wrOOGBvQnDny0.jpg' },
        name: 'DSLR Camera',
        description: '24MP, 4K Video recording',
        actualPrice: 599,
        discountPrice: 499,
        shopName: 'PhotoPro',
        rating: 4.8,
    },
    {
        id: '7',
        image: { uri: 'https://images.unsplash.com/photo-1580584126903-c17d7b7ee6c0?auto=format&fit=crop&w=600&q=60' },
        name: 'Gaming Keyboard',
        description: 'Mechanical, RGB backlit',
        actualPrice: 89,
        discountPrice: 69,
        shopName: 'GameZone',
        rating: 4.5,
    },
    {
        id: '8',
        image: { uri: 'https://images.unsplash.com/photo-1573855042769-4a2f0a1f2143?auto=format&fit=crop&w=600&q=60' },
        name: '4K Monitor',
        description: '27", Ultra HD display',
        actualPrice: 329,
        discountPrice: 279,
        shopName: 'DisplayWorld',
        rating: 4.6,
    },
    {
        id: '9',
        image: { uri: 'https://images.unsplash.com/photo-1616627981834-ecb6c751f1c6?auto=format&fit=crop&w=600&q=60' },
        name: 'Smartphone',
        description: '128GB, 6.5-inch AMOLED',
        actualPrice: 799,
        discountPrice: 699,
        shopName: 'Tech Hub',
        rating: 4.9,
    },
    {
        id: '10',
        image: { uri: 'https://images.unsplash.com/photo-1618401472820-5cd16f7edfe0?auto=format&fit=crop&w=600&q=60' },
        name: 'Tablet',
        description: '10.1" display, stylus supported',
        actualPrice: 399,
        discountPrice: 349,
        shopName: 'Tablet Plus',
        rating: 4.3,
    },
    {
        id: '11',
        image: { uri: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=60' },
        name: 'Laptop Stand',
        description: 'Adjustable, aluminum body',
        actualPrice: 45,
        discountPrice: 30,
        shopName: 'Office Gear',
        rating: 4.2,
    },
    {
        id: '12',
        image: { uri: 'https://images.unsplash.com/photo-1611078489935-b8f6fc5651c2?auto=format&fit=crop&w=600&q=60' },
        name: 'Webcam',
        description: '1080p Full HD, USB',
        actualPrice: 65,
        discountPrice: 49,
        shopName: 'Stream Store',
        rating: 4.4,
    },
    {
        id: '13',
        image: { uri: 'https://images.unsplash.com/photo-1611175694983-5a7be5d3bda7?auto=format&fit=crop&w=600&q=60' },
        name: 'Portable SSD',
        description: '1TB, USB-C',
        actualPrice: 199,
        discountPrice: 159,
        shopName: 'StorageMax',
        rating: 4.8,
    },
    {
        id: '14',
        image: { uri: 'https://images.unsplash.com/photo-1627585104447-393d26b2f3c7?auto=format&fit=crop&w=600&q=60' },
        name: 'LED Desk Lamp',
        description: 'Touch control, dimmable',
        actualPrice: 39,
        discountPrice: 25,
        shopName: 'Light House',
        rating: 4.1,
    },
    {
        id: '15',
        image: { uri: 'https://images.unsplash.com/photo-1617979140094-5e21d12c5a47?auto=format&fit=crop&w=600&q=60' },
        name: 'Electric Kettle',
        description: '1.5L, auto shut-off',
        actualPrice: 49,
        discountPrice: 35,
        shopName: 'Kitchen King',
        rating: 4.4,
    },
    {
        id: '16',
        image: { uri: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=60' },
        name: 'Office Chair',
        description: 'Ergonomic, adjustable height',
        actualPrice: 180,
        discountPrice: 140,
        shopName: 'FurniCo',
        rating: 4.6,
    },
];
